name: build

on:
  push:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      BUNDLE_PATH: ../../../../.gem
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
      FLUTTER_VERSION: '3.16.7'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Check Java version
        run: |
          echo "JAVA_HOME is $JAVA_HOME"
          java -version
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Set up local.properties
        run: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          rubygems: latest
          bundler-cache: false

      - name: Get bundler
        run: |
           gem install bundler -v 2.5.18

      - name: Build and deploy with Fastlane
        run: |
          flutter pub get
          make deploy-android
